"""add sort_order to assets alerts watchlist

Revision ID: 249bba56d7a1
Revises: ea17d9be8248
Create Date: 2026-04-02 23:49:15.572516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '249bba56d7a1'
down_revision: Union[str, None] = 'ea17d9be8248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_assets_sort_order'), 'assets', ['sort_order'], unique=False)
    op.add_column('price_alerts', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_price_alerts_sort_order'), 'price_alerts', ['sort_order'], unique=False)
    op.add_column('watchlist', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_watchlist_sort_order'), 'watchlist', ['sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_sort_order'), table_name='watchlist')
    op.drop_column('watchlist', 'sort_order')
    op.drop_index(op.f('ix_price_alerts_sort_order'), table_name='price_alerts')
    op.drop_column('price_alerts', 'sort_order')
    op.drop_index(op.f('ix_assets_sort_order'), table_name='assets')
    op.drop_column('assets', 'sort_order')
    # ### end Alembic commands ###
