"""modify_webhook_url_nullable

Revision ID: 73109a799b57
Revises: 5dbb97e2b6ee
Create Date: 2026-03-26 03:46:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73109a799b57'
down_revision: Union[str, None] = '5dbb97e2b6ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 对于SQLite，需要重建表来修改列约束
    op.execute('''
        CREATE TABLE price_alerts_new (
            id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            crypto_id INTEGER NOT NULL,
            alert_type VARCHAR(50) NOT NULL,
            threshold_price FLOAT NOT NULL,
            webhook_url VARCHAR(500),
            is_active BOOLEAN DEFAULT 1,
            triggered_at DATETIME,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (id),
            FOREIGN KEY(user_id) REFERENCES users (id),
            FOREIGN KEY(crypto_id) REFERENCES cryptocurrencies (id)
        )
    ''')
    
    # 复制数据
    op.execute('''
        INSERT INTO price_alerts_new (id, user_id, crypto_id, alert_type, threshold_price, webhook_url, is_active, triggered_at, created_at)
        SELECT id, user_id, crypto_id, alert_type, threshold_price, webhook_url, is_active, triggered_at, created_at
        FROM price_alerts
    ''')
    
    # 删除旧表
    op.execute('DROP TABLE price_alerts')
    
    # 重命名新表
    op.execute('ALTER TABLE price_alerts_new RENAME TO price_alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 对于SQLite，需要重建表来恢复列约束
    op.execute('''
        CREATE TABLE price_alerts_old (
            id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            crypto_id INTEGER NOT NULL,
            alert_type VARCHAR(50) NOT NULL,
            threshold_price FLOAT NOT NULL,
            webhook_url VARCHAR(500) NOT NULL,
            is_active BOOLEAN DEFAULT 1,
            triggered_at DATETIME,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (id),
            FOREIGN KEY(user_id) REFERENCES users (id),
            FOREIGN KEY(crypto_id) REFERENCES cryptocurrencies (id)
        )
    ''')
    
    # 复制数据
    op.execute('''
        INSERT INTO price_alerts_old (id, user_id, crypto_id, alert_type, threshold_price, webhook_url, is_active, triggered_at, created_at)
        SELECT id, user_id, crypto_id, alert_type, threshold_price, COALESCE(webhook_url, ''), is_active, triggered_at, created_at
        FROM price_alerts
    ''')
    
    # 删除旧表
    op.execute('DROP TABLE price_alerts')
    
    # 重命名新表
    op.execute('ALTER TABLE price_alerts_old RENAME TO price_alerts')
    # ### end Alembic commands ###