"""add_api_settings

Revision ID: bb05fff643b5
Revises: 73109a799b57
Create Date: 2026-03-26 03:57:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb05fff643b5'
down_revision: Union[str, None] = '73109a799b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('primary_api_url', sa.String(length=500), nullable=True, comment='主API地址'),
    sa.Column('backup_api_url', sa.String(length=500), nullable=True, comment='备用API地址'),
    sa.Column('api_key', sa.String(length=500), nullable=True, comment='API密钥'),
    sa.Column('api_secret', sa.String(length=500), nullable=True, comment='API密钥'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_api_settings_id'), 'api_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_settings_id'), table_name='api_settings')
    op.drop_table('api_settings')
    # ### end Alembic commands ###