"""add notification_channel and notification_group to price_alerts

Revision ID: c5814252a5ee
Revises: 03bd92ee43bb
Create Date: 2026-04-06 10:53:04.120020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5814252a5ee'
down_revision: Union[str, None] = '03bd92ee43bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_alerts', sa.Column('notification_channel', sa.String(length=100), nullable=True, comment='通知渠道名称'))
    op.add_column('price_alerts', sa.Column('notification_group', sa.String(length=100), nullable=True, comment='通知频道名称'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_alerts', 'notification_group')
    op.drop_column('price_alerts', 'notification_channel')
    # ### end Alembic commands ###
