"""add_alert_histories

Revision ID: dcd4fc453d1c
Revises: bb05fff643b5
Create Date: 2026-03-26 10:17:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd4fc453d1c'
down_revision: Union[str, None] = 'bb05fff643b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('crypto_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=20), nullable=False),
    sa.Column('threshold_price', sa.Float(), nullable=False),
    sa.Column('trigger_price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('TRIGGERED', 'NOTIFIED', 'FAILED', name='alerthistorystatus'), nullable=True),
    sa.Column('notification_sent', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['price_alerts.id'], ),
    sa.ForeignKeyConstraint(['crypto_id'], ['cryptocurrencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_histories_id'), 'alert_histories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_histories_id'), table_name='alert_histories')
    op.drop_table('alert_histories')
    # ### end Alembic commands ###